---
pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest
name: springpet
trigger:
  - main
stages:
  - stage: stage1
    displayName: spring-stage1
    jobs:
      - job: job1
        displayName: spring-job1
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
              
