version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: "database"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - type: bind
        source: "./conf.d"
        target: "/etc/mysql/conf.d:ro"
      - type: bind
        source: "./mysql/data"
        target: "/var/lib/mysql"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 5s    
    restart: unless-stopped
  
  frontend:
    image: localhost:5000/petclinic
    container_name: frontend
    environment:
      - DATABASE=mysql
      - "JAVA_OPTS=-Xms64M -Xmx512M"
    ports: 
      - "8080:8080"
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "curl -f -I http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s      
    restart: on-failure
