services:
  petclinic:
    image: samanthayeep/petclinic:latest
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:mysql://db:3307/petclinic
      - DATABASE_USERNAME=petclinic
      - DATABASE_PASSWORD=petclinicpassword

  db:
    image: my-mysql-image
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinicpassword
    ports:
      - "3307:3306"
