services:
  petclinic:
    image: spring-petclinic-petclinic
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: petclinic
    depends_on:
      postgres: 
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: postgres
      POSTGRES_URL: ${DATABASE_URL}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}

  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:




 
