dependencies:
- name: feature-server
  alias: feature-server
  version: 0.28.0
  condition: feature-server.enabled
  repository: https://feast-helm-charts.storage.googleapis.com
- name: transformation-service
  alias: transformation-service
  version: 0.28.0
  condition: transformation-service.enabled
  repository: https://feast-helm-charts.storage.googleapis.com
- name: redis
  version: 10.5.6
  repository: https://charts.helm.sh/stable
  condition: redis.enabled