apiVersion: v1
description: "Feast Feature Server: Online feature serving service for Feast"
name: feature-server
version: 0.28.0
appVersion: v0.28.0
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast