apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pet-clinic
  namespace: staging
spec:
  selector:
    matchLabels:
      app: pet-clinic

  template:
    metadata:
      labels:
        app: pet-clinic
        version: pet-c55dfe3

    spec:
      containers:
        - name: pet-clinic
          image: "jenkinsdemosacr.azurecr.io/pet-c55dfe3"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: "acr-secret"
