apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pet-clinic
  namespace: staging
spec:
  selector:
    matchLabels:
      app: pet-clinic

  template:
    metadata:
      labels:
        app: pet-clinic
        version: pc-55d6000

    spec:
      containers:
        - name: pet-clinic
          image: "jenkinsdemosacr.azurecr.io/pet-clinic:pc-55d6000"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: "acr-secret"
