kind: Service
apiVersion: v1
metadata:
  name: pet-clinic
  namespace: staging
  labels:
    version: pc-4c3cbd6
spec:
  type: LoadBalancer
  selector:
    app: pet-clinic
    version: pc-4c3cbd6
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
