apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  namespace: petclinic-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: petclinic-db-secret      # 실제 생성될 k8s Secret 이름
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-2:723926525504:secret:rds!db-6b52b01a-5c9d-4ff6-b787-d67320379683-mhNAu6   # master_user_secret_arn
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-2:723926525504:secret:rds!db-6b52b01a-5c9d-4ff6-b787-d67320379683-mhNAu6   # 같은 ARN
        property: password
