apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic-ns
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
    - name: http
      port: 80          # 클러스터 내부에서 볼 포트
      targetPort: http  # 위 컨테이너 포트 이름
