apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  namespace: petclinic-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretmanager
    kind: ClusterSecretStore
  target:
    name: petclinic-db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: finalproj-dev-petclinic-db   # 예: GCP Secret 이름
        property: jdbc_url                # secret value가 JSON일 때 property 사용
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: finalproj-dev-petclinic-db
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: finalproj-dev-petclinic-db
        property: password
