apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secretmanager
spec:
  provider:
    gcpsm:
      projectID: kdt2-final-project-t2
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast3
          clusterName: k8s-gke
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

