---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
data:
  application.properties: |-
{{ .Files.Get "files/application.properties" | indent 4 }}
