version: '3.3'
services:
  web:
      container_name: spring
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      depends_on:
        - mysql-server
      ports:
        - 80:8080
      networks:
        - conti-test

  mysql-server:
    image: mysql:5.6
    command: --init-file /data/application/init.sql
    volumes: 
      - ./application/init.sql:/data/application/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - conti-test

networks:
  conti-test:
    driver: bridge
