apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-plain
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-plain
  template:
    metadata:
      labels:
        app: spring-petclinic-plain
    spec:
      containers:
        - name: spring-petclinic-plain
          image: localhost:9092/petclinic-plain:1
          ports:
            - containerPort: 8080
              name: http
