name: CI Pipeline for Develop Branch

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Job 1: checkout-and-version
  checkout-and-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-info.outputs.version }}
      artifact_id: ${{ steps.extract-info.outputs.artifact_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Extract info from pom.xml
        id: extract-info
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          ARTIFACT_ID=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          

  # Job 2.1: linting
  linting:
    needs: checkout-and-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle
        # Run the Check but Don't Fail the Build
        run: ./mvnw -B checkstyle:check -Dcheckstyle.failOnViolation=false

  # Job 2.2: unit-tests
  unit-tests:
    needs: checkout-and-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: ./mvnw -B test

  # Job 2.3: secret-scan
  secret-scan:
    needs: checkout-and-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # IMPORTANT: fetch-depth 0 is required to scan the entire history
        with:
          fetch-depth: 0

      - name: Scan for hardcoded secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          # Do NOT provide 'base' or 'head' here to ensure it scans everything
          extra_args: --only-verified --results=verified

  # Job 2.4: sast-scan
  sast-scan:
    needs: checkout-and-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Scan for vulnerabilities
        uses: AppThreat/sast-scan-action@master
        with:
          type: "java"

  # Job 3:
  build-binary-and-image-and-scan:
    needs: [linting, unit-tests, secret-scan, sast-scan, checkout-and-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: ./mvnw -B clean package -DskipTests

      - name: Build Container image
        run: |
          APP_NAME=${{ needs.checkout-and-version.outputs.artifact_id }}
          APP_VERSION=${{ needs.checkout-and-version.outputs.version }}
          APP_JAR=${APP_NAME}-${APP_VERSION}.jar
          
          docker build \
            --build-arg APP_JAR=${APP_JAR}
            --build-arg COMMIT_SHA=${{ github.sha }} \
            --build-arg VERSION=${APP_VERSION} \
            -t ${APP_NAME}:${APP_VERSION} .
          
          docker tag ${APP_NAME}:${APP_VERSION} ${APP_NAME}:latest

      - name: Scan Container image
        run: |
          echo "Run image scan..."

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.checkout-and-version.outputs.artifact_id }}-${{ needs.checkout-and-version.outputs.version }}
          path: target/*.jar


  # Job 4.1: push-binary
  push-binary:
    needs: [build-binary-and-image-and-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: app-binary-${{ needs.checkout-and-version.outputs.version }}

      - name: Push to artifact repository
        run: |
          echo "Push artifact: ${{ needs.checkout-and-version.outputs.version }}/app.jar"

  # Job 4.2: push-image
  push-image:
    needs: [build-binary-and-image-and-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "Login image repository..."

      - name: Push Docker image
        run: |
          echo "Push image: docker push myapp:${{ needs.checkout-and-version.outputs.version }}""

  # Job 5: notify-status (Always runs)
  notify-status:
    needs: [push-binary, push-image]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send email notification
        run: |
          echo "Send Email notifacation: CI Status: ${{ job.status }}"

  # Job 6: trigger-cd (Only on full success)
  trigger-cd:
    needs: [push-binary, push-image, notify-status]
    runs-on: ubuntu-latest
    if: ${{ needs.push-binary.result == 'success' && needs.push-image.result == 'success' && needs.notify-status.result == 'success' }}
    steps:
      - name: Trigger CD Pipeline
        run: |
          echo "Trigger CD pipeline..."
