name: Yaml file in Spring Boot clinic

on: 

    push:

        branches:
            
            main
    
    workflow_dispatch:

jobs:
    maven-building:
        runs-on: ubuntu-latest
        steps:
            - name: first_step
              uses: actions/checkout@v4
            - name: second_step
              run: mvn package
