name: Development pipeline
on:
  push:
    branches:
      kubify
  pull_request:
    branches:
      main
  release:
    types: 
      published
jobs:
  build:
    name: Build spring boot application and package jars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: mvn -B package --file pom.xml
    - run: mvn --batch-mode --update-snapshots verify
    - uses: actions/upload-artifact@v2
      with:
        name: application-jars
        path: target
  package:
    name: Build Docker image and push to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Retrieve jars
      uses: actions/download-artifact@v2
      with:
        name: application-jars
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: PrepareReg Names
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
    - id: docker-build-push
      name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ env.IMAGE_REPOSITORY }}/spring-petclinic-image:${{ github.sha }}