name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.meta.outputs.tags }}
      
    steps:
    #checkout repo
    - uses: actions/checkout@v3

    #build docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spring-petclinic:latest

    #login to github container registry
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    #get metadeta
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/${{ github.repository }}

    #build/push to ghcr
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
  ecr-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    #aws authentication
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    #image setup
    - name: Pull Docker image from GHCR
      run: docker pull ghcr.io/${{ github.repository }}/${{ needs.docker-build.outputs.docker_tag }}

    - name: Tag the image for ECR
      run: docker tag ${{ needs.docker-build.outputs.docker_tag }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/spring-petclinic:latest

    #push image
    - name: Push image to Amazon ECR
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/spring-petclinic:latest
