---

name : Java with maven
on: 
   push
 
jobs: 
  build:
    name:  "maven" 
    runs-on: ubuntu-latest
    steps: 
      - name: My first step
        run: mvn package
      - uses:  actions/checkout@v4 
       



